"""add_celery_task_records_table

Revision ID: 0429c91fc4c7
Revises: 5654e9c2f928
Create Date: 2026-05-11 15:00:00.254459

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0429c91fc4c7'
down_revision: Union[str, Sequence[str], None] = '5654e9c2f928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_task_records', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.add_column('celery_task_records', sa.Column('updated_by', sa.Uuid(), nullable=True))
    # 创建新枚举类型并转换
    new_status_enum = sa.Enum(
        'PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='celerytaskstatus'
    )
    new_status_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        'celery_task_records',
        'status',
        existing_type=postgresql.ENUM(
            'PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='taskstatus'
        ),
        type_=new_status_enum,
        existing_nullable=False,
        postgresql_using='status::text::celerytaskstatus',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'celery_task_records',
        'status',
        existing_type=sa.Enum(
            'PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='celerytaskstatus'
        ),
        type_=postgresql.ENUM(
            'PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='taskstatus'
        ),
        existing_nullable=False,
    )
    op.drop_column('celery_task_records', 'updated_by')
    op.drop_column('celery_task_records', 'created_by')
    # ### end Alembic commands ###
