"""set InspectionRecordModel field type and defaul

Revision ID: 087733a63533
Revises: 8ae8f2df9525
Create Date: 2026-04-21 15:49:45.396615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087733a63533'
down_revision: Union[str, Sequence[str], None] = '8ae8f2df9525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspectionresultenum = sa.Enum('NORMAL', 'REQUIRES_CORRECTION', 'IN_PROGRESS', 'COMPLETED', name='inspectionresultenum')
    inspectionresultenum.create(op.get_bind(), checkfirst=True)
    op.alter_column('inspection_record', 'status',
               existing_type=sa.VARCHAR(),
               type_=inspectionresultenum,
               existing_nullable=False,
               postgresql_using='status::inspectionresultenum')
    op.alter_column('inspection_record', 'ai_detection_execute_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('inspection_record', 'ai_inspection_excute_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection_record', 'ai_inspection_excute_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inspection_record', 'ai_detection_execute_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inspection_record', 'status',
               existing_type=sa.Enum('NORMAL', 'REQUIRES_CORRECTION', 'IN_PROGRESS', 'COMPLETED', name='inspectionresultenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
