"""add_task_records_table

Revision ID: 488ca7d5c88f
Revises: 0429c91fc4c7
Create Date: 2026-05-13 12:30:47.122427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '488ca7d5c88f'
down_revision: Union[str, Sequence[str], None] = '0429c91fc4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_celery_task_records_related_record_id'), table_name='celery_task_records')
    op.drop_index(op.f('ix_celery_task_records_status'), table_name='celery_task_records')
    op.drop_index(op.f('ix_celery_task_records_task_id'), table_name='celery_task_records')
    op.drop_index(op.f('ix_celery_task_records_task_name'), table_name='celery_task_records')
    op.drop_table('celery_task_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_records',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('kwargs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='celerytaskstatus'), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('worker_hostname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('related_record_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_task_records_pkey'))
    )
    op.create_index(op.f('ix_celery_task_records_task_name'), 'celery_task_records', ['task_name'], unique=False)
    op.create_index(op.f('ix_celery_task_records_task_id'), 'celery_task_records', ['task_id'], unique=True)
    op.create_index(op.f('ix_celery_task_records_status'), 'celery_task_records', ['status'], unique=False)
    op.create_index(op.f('ix_celery_task_records_related_record_id'), 'celery_task_records', ['related_record_id'], unique=False)
    # ### end Alembic commands ###
