"""update_FileReferenceModel

Revision ID: 5654e9c2f928
Revises: af3e79c6750c
Create Date: 2026-05-08 15:26:54.167033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5654e9c2f928'
down_revision: Union[str, Sequence[str], None] = 'af3e79c6750c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bucket_enum = sa.Enum('IMAGE', 'PDF', 'COMPRESSED_FILE', 'UNKNOWN', name='gridfsbucketnameenum')
    bucket_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('file_references', sa.Column('bucket_name_type', bucket_enum, nullable=False))
    op.drop_index(op.f('ix_file_references_storage_type'), table_name='file_references')
    op.create_index(op.f('ix_file_references_bucket_name_type'), 'file_references', ['bucket_name_type'], unique=False)
    op.drop_column('file_references', 'storage_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_references', sa.Column('storage_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_file_references_bucket_name_type'), table_name='file_references')
    op.create_index(op.f('ix_file_references_storage_type'), 'file_references', ['storage_type'], unique=False)
    op.drop_column('file_references', 'bucket_name_type')
    # ### end Alembic commands ###
