"""update_ai_inspection_models

Revision ID: af3e79c6750c
Revises: ee7ff036824b
Create Date: 2026-05-08 14:06:01.377395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3e79c6750c'
down_revision: Union[str, Sequence[str], None] = 'ee7ff036824b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_execute_task', 'file_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='file_id::uuid')
    op.add_column('inspection_record', sa.Column('file_id', sa.Uuid(), nullable=False))
    op.drop_column('inspection_record', 'image_gridfs_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_record', sa.Column('image_gridfs_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('inspection_record', 'file_id')
    op.alter_column('ai_execute_task', 'file_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
