"""add_file_references_and_auth_tables

Revision ID: d5f7a079700c
Revises: 087733a63533
Create Date: 2026-04-28 15:42:18.560392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f7a079700c'
down_revision: Union[str, Sequence[str], None] = '087733a63533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_references', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.add_column('file_references', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_file_references_uploaded_by'), table_name='file_references')
    op.drop_column('file_references', 'uploaded_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_references', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_file_references_uploaded_by'), 'file_references', ['uploaded_by'], unique=False)
    op.drop_column('file_references', 'updated_by')
    op.drop_column('file_references', 'created_by')
    # ### end Alembic commands ###
