"""update_file_references_fields

Revision ID: ee7ff036824b
Revises: d5f7a079700c
Create Date: 2026-05-08 12:27:35.526163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7ff036824b'
down_revision: Union[str, Sequence[str], None] = 'd5f7a079700c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_execute_task', sa.Column('file_id', sa.String(), nullable=False))
    op.drop_column('ai_execute_task', 'image_gridfs_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_execute_task', sa.Column('image_gridfs_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ai_execute_task', 'file_id')
    # ### end Alembic commands ###
